blog_post/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_posts.urls'))
]

blog_posts/urls.py
"""Defines URL patterns for blog Posts"""

from django.urls import path
from . import views

app_name = 'blog_posts'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all categories
    path('categories/', views.categories, name='categories'),
    # page 
]

blog_posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', args=[self.slug])


class Post(models.Model):
    content = models.TextField()
    publication_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='post_images', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.post.title}'

blog_posts/views.py
from django.shortcuts import render
from .models import Category

def index(request):
    """The home page for the app"""
    return render(request, 'blog_posts/index.html')

def categories(request):
    """Show all categories"""
    categories = Category.objects.order_by('name')
    context = {'categories': categories}
    return render(request, 'blog_posts/categories.html', context)

blog_posts/templates/blog_posts/base.html
<p>
    <a href="{% url 'blog_posts:index'%}">Blog Posts</a>
    <a href="{% url 'blog_posts:categories'%}">Categories</a>
</p>

{% block content %}{% endblock content %}

blog_posts/templates/blog_posts/categories.html
{% extends 'blog_posts/base.html' %}

{% block content %}
    <p>Categories:</p>

    <ul>
        {% for item in categories %}
          <li>{{ item }}</li>

        {% empty %}
          <li>No category added yet.</li>
          
        {% endfor %}
    </ul>

{% endblock content %}

blog_posts/templates/blog_posts/index.html
{% extends 'blog_posts/base.html' %}

{% block content %}
  <h1>Welcome to my Blog<h2>

    <p>This app enables you to write blog on topics you study or trending
      issues around the globe.
    </p>

{% endblock content %}